6213-100503D Попов Виктор Игоревич Лаб.3 Вар.5
itsecd/application-programming-labs pull request #139
Opened 2024-10-29 19:14 UTC by Vantany

**ФИО:** Попов Виктор
**Номер группы:** 6213
**Номер лабораторной:** 3
**Номер варианта:** 05  
**Краткое описание решаемой задачи:** Согласно варианту 5 лабораторной 3 мне надо было открыть изображение, построить для него гистограмму с помощью библиотеки OpenCv, а также инвертировать цвета в картинке, после чего вывести обе картинки на экран с помощью библиотеки matplotlib.  
**Краткое описание работы кода:** Функция get_arguments считывает необходимы аргументы из командной строки. Модуль img_actions.py отвечает за работу с библиотекой OpenCV непосредственно, в нем происходят все нужные по заданию операции над изображением. Модуль histogram_actions.py отвечает за построение гистограммы изображении и успешный вывод графика на экран.

2024-10-30 10:11 UTC, vfkon requested changes
Функция show_images сделана неправильно. Вы же знаете что будет передано и описываете это в docstring, почему это передается в виде kwargs и args и никак не првоеряется? Exceptionы тоже замечательные, почему Raise в блоке except, а не try? почему Exception самый общий, а не конкретный, и сообщение о исключении теряется? если кода много, найти в какой строчке и где оно произошло без stacktrace, который включен в стандартное сообщение о исключении будет невозможно. imread надо проверять, поскольку при невозможности чтения он тихо возвращает None, не бросая исключение. В парсере нет подсказок о назначении аргументов, а сами они имеют непонятные названия

2024-10-30 16:10 UTC, Vantany commented
Добрый вечер, исправил полученные замечания, хотел сделать нестандартную реализацию функции show_images, позволяющую выводить на экран любое колличество изображений (сейчас переделал на необходимую в заданию реализацию), Exceptionы сейчас поставил в тех местах в которых они могут происходить.

2024-11-01 12:42 UTC, Vantany commented
Исправления сделаны, на лабораторной вы зачли все

2024-11-01 13:16 UTC, vfkon approved these changes
Зачтено

2025-02-04 16:12 UTC, closed without merging