6213-100503D Никишин Владислав Леонидович Лаб.2 Вар.1
itsecd/application-programming-labs pull request #189
Opened 2024-11-08 12:29 UTC by h0shi-tech

**ФИО:** Фамилия Имя  
**Номер группы:** 6213  
**Номер лабораторной:** 2 
**Номер варианта:** 1  
**Краткое описание решаемой задачи:** Согласно варианту мне нужно было скачать изображения с помощью краулера, составить аннотацию в виде csv файла и написать итератор по изображениям
**Краткое описание работы кода:** Описано в комментариях кода

2024-11-08 13:00 UTC, vfkon requested changes
ФИО: Фамилия Имя. Ну и все же описание работы кода лучше помещать вне кода. Вы же не будете пользователей в код посылать. Нет typehints и docstring. Аргументы мы получаем из командной строки с помощью argparse. В остальном ок

2024-11-08 13:06 UTC, h0shi-tech commented
ФИО: Никишин Влад
В представленном коде реализуется процесс краулинга (сбора) изображений с интернет-ресурсов, таких как Google и Bing, по ключевому слову, с последующим сохранением путей к этим изображениям в CSV файл и возможностью итерации по собранным данным.

2024-11-08 13:08 UTC, h0shi-tech commented
docstring и typehints добавил в код.  Могу показать в классе  ( ͡❛ ͜ʖ ͡❛)

2024-11-15 06:47 UTC, h0shi-tech commented
Ой :) Не в ту ветку)))

2024-11-22 11:42 UTC, vfkon approved these changes
Зачтено

2025-02-04 16:16 UTC, closed without merging